### PR TITLE
closed #69

### LINKED ISSUE #69: [Bug] Matpaginator doesn't reset when changing specialization.
On https://omscentral.com/courses, 

1. if we first click second page for ALL and then choose CPR specialization, no course could be shown.

2. if we first click second page for ALL and then choose CS, the courses belonging to second page will be shown. 

Based on the previous facts, we could draw a conclusion that paginator doesn't reset on ngOnInit().

### PR DESCRIPTION
**Pull request by yogykwan**
Reset Matpaginator when changing specialization.

### CODE REVIEW

**Comment by martzcodes** [comment]
this doesn't look like the correct fix for #69 ... setting a generic setTimeout may work (? untested) in practice but really it should be a click handler on changing the specialization that resets the paginator.

**Comment by yogykwan** [comment]
Actually, I tested it on chrome and it worked. Find more here. https://stackoverflow.com/questions/48785965/angular-matpaginator-not-working

**Comment by martzcodes** [comment]
i'm sure it technically works, but it seems odd to me to set a setTimeout with 0 time... you usually use that to immediately execute something but given the context of the code this isn't the right place to do that.

**Comment by yogykwan** [comment]
I agree with you. Actually I just happened to find this bug, found the root cause and searched for a solution. Not expert indeed. It’s totally fine to close my pr and fix it in your better way!

**Comment by martzcodes** [comment]
you're welcome to add it as a PR for the on click... but this PR isn't the one

**Comment by yogykwan** [comment]
Yeah, onClick will work but the workflow may be not generic for other potential items that need to be reset. Do you think putting the resetting code into ngAfterViewInit() is a good solution? This will not use setTimeout.

**Comment by martzcodes** [comment]
(Disclaimer: haven’t looked at the code recently) I mean the pagination reset should happen when you click the button to change the specialization

**Pull request closed without merging**
